package javax.swing;

/**
 * Data-only stub for {@code javax.swing.AbstractAction}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public abstract class AbstractAction implements javax.swing.Action {
    public AbstractAction() { }
    public AbstractAction(java.lang.String a0) { }
    public java.lang.Object getValue(java.lang.String a0) { return null; }
    public boolean isEnabled() { return false; }
    public void putValue(java.lang.String a0, java.lang.Object a1) { return; }
    public void addPropertyChangeListener(java.beans.PropertyChangeListener a0) { return; }
    public void removePropertyChangeListener(java.beans.PropertyChangeListener a0) { return; }
    public void setEnabled(boolean a0) { return; }
    public void actionPerformed(java.awt.event.ActionEvent a0) { return; }
}
