package javax.swing;

/**
 * Data-only stub for {@code javax.swing.AbstractButton}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public abstract class AbstractButton extends javax.swing.JComponent implements java.awt.ItemSelectable, javax.swing.SwingConstants {
    public AbstractButton() { super(); }
    public void addItemListener(java.awt.event.ItemListener a0) { return; }
    public javax.swing.ButtonModel getModel() { return null; }
    public javax.swing.Icon getRolloverIcon() { return null; }
    public javax.swing.Icon getRolloverSelectedIcon() { return null; }
    public boolean isRolloverEnabled() { return false; }
    public boolean isSelected() { return false; }
    public void putClientProperty(java.lang.Object a0, java.lang.Object a1) { return; }
    public void setToolTipText(java.lang.String a0) { return; }
}
