package javax.swing;

/**
 * Data-only stub for {@code javax.swing.BorderFactory}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class BorderFactory {
    public static javax.swing.border.CompoundBorder createCompoundBorder(javax.swing.border.Border a0, javax.swing.border.Border a1) { return null; }
    public static javax.swing.border.Border createEmptyBorder(int a0, int a1, int a2, int a3) { return null; }
    public static javax.swing.border.Border createLineBorder(java.awt.Color a0) { return null; }
    public static javax.swing.border.Border createLineBorder(java.awt.Color a0, int a1) { return null; }
    public static javax.swing.border.MatteBorder createMatteBorder(int a0, int a1, int a2, int a3, java.awt.Color a4) { return null; }
}
