package javax.swing;

/**
 * Data-only stub for {@code javax.swing.DefaultListCellRenderer}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class DefaultListCellRenderer extends javax.swing.JLabel implements javax.swing.ListCellRenderer {
    public DefaultListCellRenderer() { super(); }
    public java.awt.Component getListCellRendererComponent(javax.swing.JList a0, java.lang.Object a1, int a2, boolean a3, boolean a4) { return null; }
}
