package javax.swing;

/**
 * Data-only stub for {@code javax.swing.DefaultListModel}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class DefaultListModel extends javax.swing.AbstractListModel {
    public DefaultListModel() { super(); }
    public void addElement(java.lang.Object a0) { return; }
    public void addListDataListener(javax.swing.event.ListDataListener a0) { return; }
    public void clear() { return; }
    public java.lang.Object get(int a0) { return null; }
    public boolean isEmpty() { return false; }
    public int getSize() { return 0; }
    public java.lang.Object getElementAt(int a0) { return null; }
}
