package javax.swing;

/**
 * Data-only stub for {@code javax.swing.GroupLayout}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class GroupLayout implements java.awt.LayoutManager2 {
    public GroupLayout(java.awt.Container a0) { }
    public javax.swing.GroupLayout.ParallelGroup createParallelGroup() { return null; }
    public javax.swing.GroupLayout.ParallelGroup createParallelGroup(javax.swing.GroupLayout.Alignment a0) { return null; }
    public javax.swing.GroupLayout.SequentialGroup createSequentialGroup() { return null; }
    public void setHorizontalGroup(javax.swing.GroupLayout.Group a0) { return; }
    public void setVerticalGroup(javax.swing.GroupLayout.Group a0) { return; }
    public void addLayoutComponent(java.awt.Component a0, java.lang.Object a1) { return; }
    public java.awt.Dimension maximumLayoutSize(java.awt.Container a0) { return null; }
    public float getLayoutAlignmentX(java.awt.Container a0) { return 0f; }
    public float getLayoutAlignmentY(java.awt.Container a0) { return 0f; }
    public void invalidateLayout(java.awt.Container a0) { return; }
    public void addLayoutComponent(java.lang.String a0, java.awt.Component a1) { return; }
    public void removeLayoutComponent(java.awt.Component a0) { return; }
    public java.awt.Dimension minimumLayoutSize(java.awt.Container a0) { return null; }
    public java.awt.Dimension preferredLayoutSize(java.awt.Container a0) { return null; }
    public void layoutContainer(java.awt.Container a0) { return; }

    public static enum Alignment {
        BASELINE,
        CENTER,
        TRAILING,
        LEADING,
    }

    public abstract static class Group extends javax.swing.GroupLayout.Spring {
        public Group() { super(); }
    }

    public static class ParallelGroup extends javax.swing.GroupLayout.Group {
        public ParallelGroup() { super(); }
        public javax.swing.GroupLayout.ParallelGroup addComponent(java.awt.Component a0) { return null; }
        public javax.swing.GroupLayout.ParallelGroup addComponent(java.awt.Component a0, int a1, int a2, int a3) { return null; }
        public javax.swing.GroupLayout.ParallelGroup addComponent(java.awt.Component a0, javax.swing.GroupLayout.Alignment a1) { return null; }
        public javax.swing.GroupLayout.ParallelGroup addGroup(javax.swing.GroupLayout.Group a0) { return null; }
    }

    public final static class SequentialGroup extends javax.swing.GroupLayout.Group {
        public SequentialGroup() { super(); }
        public javax.swing.GroupLayout.SequentialGroup addComponent(java.awt.Component a0) { return null; }
        public javax.swing.GroupLayout.SequentialGroup addComponent(java.awt.Component a0, int a1, int a2, int a3) { return null; }
        public javax.swing.GroupLayout.SequentialGroup addGap(int a0) { return null; }
        public javax.swing.GroupLayout.SequentialGroup addGroup(javax.swing.GroupLayout.Group a0) { return null; }
        public javax.swing.GroupLayout.SequentialGroup addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement a0, int a1, int a2) { return null; }
    }

    public abstract static class Spring {
    }
}
