package javax.swing;

/**
 * Data-only stub for {@code javax.swing.ImageIcon}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class ImageIcon implements javax.swing.Icon, javax.accessibility.Accessible {
    public ImageIcon() { }
    public ImageIcon(java.awt.Image a0) { }
    public ImageIcon(java.net.URL a0) { }
    public java.awt.Image getImage() { return null; }
    public void paintIcon(java.awt.Component a0, java.awt.Graphics a1, int a2, int a3) { return; }
    public int getIconWidth() { return 0; }
    public int getIconHeight() { return 0; }
    public javax.accessibility.AccessibleContext getAccessibleContext() { return null; }
}
