package javax.swing;

/**
 * Data-only stub for {@code javax.swing.JButton}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class JButton extends javax.swing.AbstractButton implements javax.accessibility.Accessible {
    public JButton() { super(); }
    public JButton(java.lang.String a0) { super(); }
    public JButton(java.lang.String a0, javax.swing.Icon a1) { super(); }
    public JButton(javax.swing.Icon a0) { super(); }
    public void addActionListener(java.awt.event.ActionListener a0) { return; }
    public void addChangeListener(javax.swing.event.ChangeListener a0) { return; }
    public void addFocusListener(java.awt.event.FocusListener a0) { return; }
    public void addKeyListener(java.awt.event.KeyListener a0) { return; }
    public void addMouseListener(java.awt.event.MouseListener a0) { return; }
    public void addMouseMotionListener(java.awt.event.MouseMotionListener a0) { return; }
    public java.awt.Color getBackground() { return null; }
    public int getHeight() { return 0; }
    public javax.swing.ButtonModel getModel() { return null; }
    public java.awt.Dimension getPreferredSize() { return null; }
    public void paint(java.awt.Graphics a0) { return; }
    public void setAlignmentX(float a0) { return; }
    public void setAlignmentY(float a0) { return; }
    public void setBackground(java.awt.Color a0) { return; }
    public void setBorder(javax.swing.border.Border a0) { return; }
    public void setComponentPopupMenu(javax.swing.JPopupMenu a0) { return; }
    public void setDisabledIcon(javax.swing.Icon a0) { return; }
    public void setEnabled(boolean a0) { return; }
    public void setFocusPainted(boolean a0) { return; }
    public void setFocusTraversalKeysEnabled(boolean a0) { return; }
    public void setFocusable(boolean a0) { return; }
    public void setFont(java.awt.Font a0) { return; }
    public void setForeground(java.awt.Color a0) { return; }
    public void setIcon(javax.swing.Icon a0) { return; }
    public void setMaximumSize(java.awt.Dimension a0) { return; }
    public void setPreferredSize(java.awt.Dimension a0) { return; }
    public void setRolloverEnabled(boolean a0) { return; }
    public void setRolloverIcon(javax.swing.Icon a0) { return; }
    public void setSelected(boolean a0) { return; }
    public void setSelectedIcon(javax.swing.Icon a0) { return; }
    public void setText(java.lang.String a0) { return; }
    public void setToolTipText(java.lang.String a0) { return; }
    public void setUI(javax.swing.plaf.ButtonUI a0) { return; }
    public void setVisible(boolean a0) { return; }
}
