package javax.swing;

/**
 * Data-only stub for {@code javax.swing.JCheckBox}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class JCheckBox extends javax.swing.JToggleButton implements javax.accessibility.Accessible {
    public JCheckBox() { super(); }
    public JCheckBox(java.lang.String a0) { super(); }
    public JCheckBox(java.lang.String a0, boolean a1) { super(); }
    public void addActionListener(java.awt.event.ActionListener a0) { return; }
    public void addItemListener(java.awt.event.ItemListener a0) { return; }
    public boolean isSelected() { return false; }
    public void setBackground(java.awt.Color a0) { return; }
    public void setSelected(boolean a0) { return; }
}
