package javax.swing;

/**
 * Data-only stub for {@code javax.swing.JComponent}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public abstract class JComponent extends java.awt.Container implements javax.swing.TransferHandler.HasGetTransferHandler {
    public JComponent() { super(); }
    public java.awt.Component add(java.awt.Component a0) { return null; }
    public void remove(java.awt.Component a0) { return; }
    public void revalidate() { return; }
    public void setComponentZOrder(java.awt.Component a0, int a1) { return; }
}
