package javax.swing;

/**
 * Data-only stub for {@code javax.swing.JComboBox}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class JComboBox extends javax.swing.JComponent implements java.awt.ItemSelectable, javax.swing.event.ListDataListener, java.awt.event.ActionListener, javax.accessibility.Accessible {
    public JComboBox(java.lang.Object[] a0) { super(); }
    public void addItemListener(java.awt.event.ItemListener a0) { return; }
    public java.awt.Dimension getPreferredSize() { return null; }
    public java.lang.Object getSelectedItem() { return null; }
    public void setPreferredSize(java.awt.Dimension a0) { return; }
    public void setRenderer(javax.swing.ListCellRenderer a0) { return; }
    public void setSelectedItem(java.lang.Object a0) { return; }
    public void setToolTipText(java.lang.String a0) { return; }
    public java.lang.Object[] getSelectedObjects() { return null; }
    public void removeItemListener(java.awt.event.ItemListener a0) { return; }
    public void contentsChanged(javax.swing.event.ListDataEvent a0) { return; }
    public void intervalAdded(javax.swing.event.ListDataEvent a0) { return; }
    public void intervalRemoved(javax.swing.event.ListDataEvent a0) { return; }
    public void actionPerformed(java.awt.event.ActionEvent a0) { return; }
}
