package javax.swing;

/**
 * Data-only stub for {@code javax.swing.JDialog}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class JDialog extends java.awt.Dialog implements javax.swing.WindowConstants, javax.accessibility.Accessible, javax.swing.RootPaneContainer, javax.swing.TransferHandler.HasGetTransferHandler {
    public JDialog() { super(); }
    public JDialog(java.awt.Window a0, java.lang.String a1, java.awt.Dialog.ModalityType a2) { super(); }
    public static void setDefaultLookAndFeelDecorated(boolean a0) { return; }
    public void setLocationRelativeTo(java.awt.Component a0) { return; }
    public void setTitle(java.lang.String a0) { return; }
    public void setGlassPane(java.awt.Component a0) { return; }
    public void setLayeredPane(javax.swing.JLayeredPane a0) { return; }
    public void setContentPane(java.awt.Container a0) { return; }
    public java.awt.Component getGlassPane() { return null; }
    public javax.swing.JRootPane getRootPane() { return null; }
    public javax.swing.JLayeredPane getLayeredPane() { return null; }
    public java.awt.Container getContentPane() { return null; }
    public javax.swing.TransferHandler getTransferHandler() { return null; }
}
