package javax.swing;

/**
 * Data-only stub for {@code javax.swing.JEditorPane}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class JEditorPane extends javax.swing.text.JTextComponent {
    public JEditorPane() { super(); }
    public JEditorPane(java.lang.String a0, java.lang.String a1) { super(); }
    public void addHyperlinkListener(javax.swing.event.HyperlinkListener a0) { return; }
    public javax.swing.text.EditorKit getEditorKitForContentType(java.lang.String a0) { return null; }
    public void removeHyperlinkListener(javax.swing.event.HyperlinkListener a0) { return; }
    public void setBorder(javax.swing.border.Border a0) { return; }
    public void setContentType(java.lang.String a0) { return; }
    public void setEditable(boolean a0) { return; }
    public void setFont(java.awt.Font a0) { return; }
    public void setForeground(java.awt.Color a0) { return; }
    public void setHighlighter(javax.swing.text.Highlighter a0) { return; }
    public void setOpaque(boolean a0) { return; }
    public void setText(java.lang.String a0) { return; }
}
