package javax.swing;

/**
 * Data-only stub for {@code javax.swing.JFileChooser}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class JFileChooser extends javax.swing.JComponent implements javax.accessibility.Accessible {
    public JFileChooser() { super(); }
    public void addChoosableFileFilter(javax.swing.filechooser.FileFilter a0) { return; }
    public java.io.File getCurrentDirectory() { return null; }
    public java.io.File getSelectedFile() { return null; }
    public java.io.File[] getSelectedFiles() { return null; }
    public boolean isMultiSelectionEnabled() { return false; }
    public void setAcceptAllFileFilterUsed(boolean a0) { return; }
    public void setCurrentDirectory(java.io.File a0) { return; }
    public void setDialogTitle(java.lang.String a0) { return; }
    public void setDialogType(int a0) { return; }
    public void setFileHidingEnabled(boolean a0) { return; }
    public void setFileSelectionMode(int a0) { return; }
    public void setMultiSelectionEnabled(boolean a0) { return; }
    public void setSelectedFile(java.io.File a0) { return; }
    public int showDialog(java.awt.Component a0, java.lang.String a1) { return 0; }
    public int showOpenDialog(java.awt.Component a0) { return 0; }
    public int showSaveDialog(java.awt.Component a0) { return 0; }
}
