package javax.swing;

/**
 * Data-only stub for {@code javax.swing.JFormattedTextField}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class JFormattedTextField extends javax.swing.JTextField {
    public JFormattedTextField() { super(); }
    public javax.swing.JFormattedTextField.AbstractFormatterFactory getFormatterFactory() { return null; }
    public void setColumns(int a0) { return; }
    public void setFormatterFactory(javax.swing.JFormattedTextField.AbstractFormatterFactory a0) { return; }
    public void setHorizontalAlignment(int a0) { return; }
    public void setValue(java.lang.Object a0) { return; }

    public abstract static class AbstractFormatter {
        public AbstractFormatter() { }
        public java.lang.Object stringToValue(java.lang.String a0) { return null; }
        public java.lang.String valueToString(java.lang.Object a0) { return null; }
    }

    public abstract static class AbstractFormatterFactory {
        public AbstractFormatterFactory() { }
        public javax.swing.JFormattedTextField.AbstractFormatter getFormatter(javax.swing.JFormattedTextField a0) { return null; }
    }
}
