package javax.swing;

/**
 * Data-only stub for {@code javax.swing.JFrame}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class JFrame extends java.awt.Frame implements javax.swing.WindowConstants, javax.accessibility.Accessible, javax.swing.RootPaneContainer, javax.swing.TransferHandler.HasGetTransferHandler {
    public JFrame() { super(); }
    public void add(java.awt.Component a0, java.lang.Object a1) { return; }
    public void addWindowListener(java.awt.event.WindowListener a0) { return; }
    public java.awt.Container getContentPane() { return null; }
    public java.awt.Dimension getMinimumSize() { return null; }
    public boolean isUndecorated() { return false; }
    public void move(int a0, int a1) { return; }
    public void pack() { return; }
    public void repaint() { return; }
    public void reshape(int a0, int a1, int a2, int a3) { return; }
    public void resize(int a0, int a1) { return; }
    public void setAlwaysOnTop(boolean a0) { return; }
    public void setContentPane(java.awt.Container a0) { return; }
    public void setDefaultCloseOperation(int a0) { return; }
    public static void setDefaultLookAndFeelDecorated(boolean a0) { return; }
    public void setIconImages(java.util.List a0) { return; }
    public void setLayout(java.awt.LayoutManager a0) { return; }
    public void setMinimumSize(java.awt.Dimension a0) { return; }
    public void setOpacity(float a0) { return; }
    public void setTitle(java.lang.String a0) { return; }
    public void setVisible(boolean a0) { return; }
    public void toFront() { return; }
    public void setGlassPane(java.awt.Component a0) { return; }
    public void setLayeredPane(javax.swing.JLayeredPane a0) { return; }
    public java.awt.Component getGlassPane() { return null; }
    public javax.swing.JRootPane getRootPane() { return null; }
    public javax.swing.JLayeredPane getLayeredPane() { return null; }
    public javax.swing.TransferHandler getTransferHandler() { return null; }
}
