package javax.swing;

/**
 * Data-only stub for {@code javax.swing.JLabel}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class JLabel extends javax.swing.JComponent implements javax.swing.SwingConstants, javax.accessibility.Accessible {
    public JLabel() { super(); }
    public JLabel(java.lang.String a0) { super(); }
    public JLabel(java.lang.String a0, int a1) { super(); }
    public JLabel(javax.swing.Icon a0) { super(); }
    public void addMouseListener(java.awt.event.MouseListener a0) { return; }
    public javax.swing.border.Border getBorder() { return null; }
    public java.awt.Font getFont() { return null; }
    public java.awt.FontMetrics getFontMetrics(java.awt.Font a0) { return null; }
    public java.awt.Color getForeground() { return null; }
    public int getHeight() { return 0; }
    public java.awt.Container getParent() { return null; }
    public java.awt.Dimension getPreferredSize() { return null; }
    public boolean isVisible() { return false; }
    public void putClientProperty(java.lang.Object a0, java.lang.Object a1) { return; }
    public void setAlignmentX(float a0) { return; }
    public void setBackground(java.awt.Color a0) { return; }
    public void setBorder(javax.swing.border.Border a0) { return; }
    public void setBounds(int a0, int a1, int a2, int a3) { return; }
    public void setBounds(java.awt.Rectangle a0) { return; }
    public void setComponentPopupMenu(javax.swing.JPopupMenu a0) { return; }
    public void setFont(java.awt.Font a0) { return; }
    public void setForeground(java.awt.Color a0) { return; }
    public void setHorizontalAlignment(int a0) { return; }
    public void setIcon(javax.swing.Icon a0) { return; }
    public void setIconTextGap(int a0) { return; }
    public void setMaximumSize(java.awt.Dimension a0) { return; }
    public void setMinimumSize(java.awt.Dimension a0) { return; }
    public void setOpaque(boolean a0) { return; }
    public void setPreferredSize(java.awt.Dimension a0) { return; }
    public void setText(java.lang.String a0) { return; }
    public void setToolTipText(java.lang.String a0) { return; }
    public void setVerticalAlignment(int a0) { return; }
    public void setVisible(boolean a0) { return; }
}
