package javax.swing;

/**
 * Data-only stub for {@code javax.swing.JLayeredPane}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class JLayeredPane extends javax.swing.JComponent implements javax.accessibility.Accessible {
    public static final java.lang.Integer DEFAULT_LAYER = null;
    public static final java.lang.Integer DRAG_LAYER = null;
    public JLayeredPane() { super(); }
    public void add(java.awt.Component a0, java.lang.Object a1) { return; }
    public void setLayout(java.awt.LayoutManager a0) { return; }
    public void setPreferredSize(java.awt.Dimension a0) { return; }
}
