package javax.swing;

/**
 * Data-only stub for {@code javax.swing.JList}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class JList extends javax.swing.JComponent implements javax.swing.Scrollable, javax.accessibility.Accessible {
    public JList() { super(); }
    public JList(javax.swing.ListModel a0) { super(); }
    public JList(java.lang.Object[] a0) { super(); }
    public void addFocusListener(java.awt.event.FocusListener a0) { return; }
    public void addListSelectionListener(javax.swing.event.ListSelectionListener a0) { return; }
    public void clearSelection() { return; }
    public java.awt.Dimension getPreferredSize() { return null; }
    public int getSelectedIndex() { return 0; }
    public java.lang.Object getSelectedValue() { return null; }
    public java.util.List getSelectedValuesList() { return null; }
    public void setCellRenderer(javax.swing.ListCellRenderer a0) { return; }
    public void setLayoutOrientation(int a0) { return; }
    public void setModel(javax.swing.ListModel a0) { return; }
    public void setPreferredSize(java.awt.Dimension a0) { return; }
    public void setSelectedIndices(int[] a0) { return; }
    public void setSelectionMode(int a0) { return; }
    public java.awt.Dimension getPreferredScrollableViewportSize() { return null; }
    public int getScrollableUnitIncrement(java.awt.Rectangle a0, int a1, int a2) { return 0; }
    public int getScrollableBlockIncrement(java.awt.Rectangle a0, int a1, int a2) { return 0; }
    public boolean getScrollableTracksViewportWidth() { return false; }
    public boolean getScrollableTracksViewportHeight() { return false; }
}
