package javax.swing;

/**
 * Data-only stub for {@code javax.swing.JMenuItem}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class JMenuItem extends javax.swing.AbstractButton implements javax.accessibility.Accessible, javax.swing.MenuElement {
    public JMenuItem() { super(); }
    public JMenuItem(java.lang.String a0) { super(); }
    public void addActionListener(java.awt.event.ActionListener a0) { return; }
    public java.awt.event.ActionListener[] getActionListeners() { return null; }
    public java.lang.String getText() { return null; }
    public void removeActionListener(java.awt.event.ActionListener a0) { return; }
    public void setText(java.lang.String a0) { return; }
    public void setVisible(boolean a0) { return; }
    public java.awt.Component getComponent() { return null; }
    public void processKeyEvent(java.awt.event.KeyEvent a0, javax.swing.MenuElement[] a1, javax.swing.MenuSelectionManager a2) { return; }
    public void processMouseEvent(java.awt.event.MouseEvent a0, javax.swing.MenuElement[] a1, javax.swing.MenuSelectionManager a2) { return; }
    public javax.swing.MenuElement[] getSubElements() { return null; }
    public void menuSelectionChanged(boolean a0) { return; }
}
