package javax.swing;

/**
 * Data-only stub for {@code javax.swing.JOptionPane}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class JOptionPane extends javax.swing.JComponent implements javax.accessibility.Accessible {
    public JOptionPane() { super(); }
    public static int showConfirmDialog(java.awt.Component a0, java.lang.Object a1, java.lang.String a2, int a3) { return 0; }
    public static int showConfirmDialog(java.awt.Component a0, java.lang.Object a1, java.lang.String a2, int a3, int a4) { return 0; }
    public static java.lang.Object showInputDialog(java.awt.Component a0, java.lang.Object a1, java.lang.String a2, int a3, javax.swing.Icon a4, java.lang.Object[] a5, java.lang.Object a6) { return null; }
    public static void showMessageDialog(java.awt.Component a0, java.lang.Object a1) { return; }
    public static void showMessageDialog(java.awt.Component a0, java.lang.Object a1, java.lang.String a2, int a3) { return; }
    public static int showOptionDialog(java.awt.Component a0, java.lang.Object a1, java.lang.String a2, int a3, int a4, javax.swing.Icon a5, java.lang.Object[] a6, java.lang.Object a7) { return 0; }
}
