package javax.swing;

/**
 * Data-only stub for {@code javax.swing.JPanel}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class JPanel extends javax.swing.JComponent implements javax.accessibility.Accessible {
    public JPanel() { super(); }
    public JPanel(java.awt.LayoutManager a0) { super(); }
    public java.awt.Component add(java.awt.Component a0) { return null; }
    public java.awt.Component add(java.awt.Component a0, int a1) { return null; }
    public void add(java.awt.Component a0, java.lang.Object a1) { return; }
    public java.awt.Component add(java.lang.String a0, java.awt.Component a1) { return null; }
    public void addComponentListener(java.awt.event.ComponentListener a0) { return; }
    public void addMouseListener(java.awt.event.MouseListener a0) { return; }
    public void addMouseMotionListener(java.awt.event.MouseMotionListener a0) { return; }
    public void addNotify() { return; }
    public void dispatchEvent(java.awt.AWTEvent a0) { return; }
    public javax.swing.ActionMap getActionMap() { return null; }
    public java.awt.Color getBackground() { return null; }
    public java.awt.Component getComponent(int a0) { return null; }
    public int getComponentCount() { return 0; }
    public javax.swing.JPopupMenu getComponentPopupMenu() { return null; }
    public java.awt.Component[] getComponents() { return null; }
    public java.awt.Cursor getCursor() { return null; }
    public javax.swing.InputMap getInputMap(int a0) { return null; }
    public java.awt.Insets getInsets() { return null; }
    public java.awt.LayoutManager getLayout() { return null; }
    public java.awt.Dimension getMaximumSize() { return null; }
    public java.awt.Dimension getMinimumSize() { return null; }
    public java.awt.Point getMousePosition(boolean a0) { return null; }
    public java.awt.Container getParent() { return null; }
    public java.awt.Dimension getPreferredSize() { return null; }
    public int getWidth() { return 0; }
    public boolean isShowing() { return false; }
    public boolean isVisible() { return false; }
    public void paint(java.awt.Graphics a0) { return; }
    public void paintComponent(java.awt.Graphics a0) { return; }
    public void remove(int a0) { return; }
    public void remove(java.awt.Component a0) { return; }
    public void removeAll() { return; }
    public void removeNotify() { return; }
    public void repaint() { return; }
    public boolean requestFocusInWindow() { return false; }
    public void revalidate() { return; }
    public void setAlignmentX(float a0) { return; }
    public void setBackground(java.awt.Color a0) { return; }
    public void setBorder(javax.swing.border.Border a0) { return; }
    public void setComponentPopupMenu(javax.swing.JPopupMenu a0) { return; }
    public void setComponentZOrder(java.awt.Component a0, int a1) { return; }
    public void setCursor(java.awt.Cursor a0) { return; }
    public void setForeground(java.awt.Color a0) { return; }
    public void setLayout(java.awt.LayoutManager a0) { return; }
    public void setMaximumSize(java.awt.Dimension a0) { return; }
    public void setMinimumSize(java.awt.Dimension a0) { return; }
    public void setOpaque(boolean a0) { return; }
    public void setPreferredSize(java.awt.Dimension a0) { return; }
    public void setSize(int a0, int a1) { return; }
    public void setToolTipText(java.lang.String a0) { return; }
    public void setVisible(boolean a0) { return; }
    public void validate() { return; }
}
