package javax.swing;

/**
 * Data-only stub for {@code javax.swing.JProgressBar}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class JProgressBar extends javax.swing.JComponent implements javax.swing.SwingConstants, javax.accessibility.Accessible {
    public JProgressBar() { super(); }
    public void setBackground(java.awt.Color a0) { return; }
    public void setBorder(javax.swing.border.Border a0) { return; }
    public void setBounds(int a0, int a1, int a2, int a3) { return; }
    public void setFont(java.awt.Font a0) { return; }
    public void setForeground(java.awt.Color a0) { return; }
    public void setMaximum(int a0) { return; }
    public void setString(java.lang.String a0) { return; }
    public void setStringPainted(boolean a0) { return; }
    public void setUI(javax.swing.plaf.ProgressBarUI a0) { return; }
    public void setValue(int a0) { return; }
}
