package javax.swing;

/**
 * Data-only stub for {@code javax.swing.JRadioButton}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class JRadioButton extends javax.swing.JToggleButton implements javax.accessibility.Accessible {
    public JRadioButton() { super(); }
    public void addActionListener(java.awt.event.ActionListener a0) { return; }
    public void setIcon(javax.swing.Icon a0) { return; }
    public void setRolloverIcon(javax.swing.Icon a0) { return; }
    public void setSelected(boolean a0) { return; }
    public void setSelectedIcon(javax.swing.Icon a0) { return; }
    public void setToolTipText(java.lang.String a0) { return; }
}
