package javax.swing;

/**
 * Data-only stub for {@code javax.swing.JRootPane}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class JRootPane extends javax.swing.JComponent implements javax.accessibility.Accessible {
    public JRootPane() { super(); }
    public java.lang.Object getClientProperty(java.lang.Object a0) { return null; }
    public void putClientProperty(java.lang.Object a0, java.lang.Object a1) { return; }
    public void registerKeyboardAction(java.awt.event.ActionListener a0, javax.swing.KeyStroke a1, int a2) { return; }
    public void setLayout(java.awt.LayoutManager a0) { return; }
    public void setWindowDecorationStyle(int a0) { return; }
}
