package javax.swing;

/**
 * Data-only stub for {@code javax.swing.JScrollPane}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class JScrollPane extends javax.swing.JComponent implements javax.swing.ScrollPaneConstants, javax.accessibility.Accessible {
    public JScrollPane() { super(); }
    public JScrollPane(java.awt.Component a0) { super(); }
    public javax.swing.JScrollBar getVerticalScrollBar() { return null; }
    public javax.swing.JViewport getViewport() { return null; }
    public void setBackground(java.awt.Color a0) { return; }
    public void setHorizontalScrollBarPolicy(int a0) { return; }
    public void setPreferredSize(java.awt.Dimension a0) { return; }
    public void setVerticalScrollBarPolicy(int a0) { return; }
    public void setViewportView(java.awt.Component a0) { return; }
    public void setVisible(boolean a0) { return; }
}
