package javax.swing;

/**
 * Data-only stub for {@code javax.swing.JScrollBar}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public abstract class JScrollBar extends javax.swing.JComponent implements java.awt.Adjustable, javax.accessibility.Accessible {
    public JScrollBar() { super(); }
    public void addAdjustmentListener(java.awt.event.AdjustmentListener a0) { return; }
    public int getMaximum() { return 0; }
    public javax.swing.BoundedRangeModel getModel() { return null; }
    public int getValue() { return 0; }
    public void setBorder(javax.swing.border.Border a0) { return; }
    public void setPreferredSize(java.awt.Dimension a0) { return; }
    public void setUnitIncrement(int a0) { return; }
    public void setValue(int a0) { return; }
}
