package javax.swing;

/**
 * Data-only stub for {@code javax.swing.JSpinner}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class JSpinner extends javax.swing.JComponent implements javax.accessibility.Accessible {
    public JSpinner() { super(); }
    public JSpinner(javax.swing.SpinnerModel a0) { super(); }
    public void addChangeListener(javax.swing.event.ChangeListener a0) { return; }
    public void addFocusListener(java.awt.event.FocusListener a0) { return; }
    public javax.swing.JComponent getEditor() { return null; }
    public javax.swing.SpinnerModel getModel() { return null; }
    public java.lang.Object getValue() { return null; }
    public void setBackground(java.awt.Color a0) { return; }
    public void setBorder(javax.swing.border.Border a0) { return; }
    public void setPreferredSize(java.awt.Dimension a0) { return; }
    public void setToolTipText(java.lang.String a0) { return; }
    public void setValue(java.lang.Object a0) { return; }

    public abstract static class DefaultEditor extends javax.swing.JPanel implements javax.swing.event.ChangeListener, java.beans.PropertyChangeListener, java.awt.LayoutManager {
        public DefaultEditor() { super(); }
        public javax.swing.JFormattedTextField getTextField() { return null; }
    }
}
