package javax.swing;

/**
 * Data-only stub for {@code javax.swing.JTable}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class JTable extends javax.swing.JComponent implements javax.swing.event.TableModelListener, javax.swing.Scrollable, javax.swing.event.TableColumnModelListener, javax.swing.event.ListSelectionListener, javax.swing.event.CellEditorListener, javax.accessibility.Accessible, javax.swing.event.RowSorterListener {
    public JTable(javax.swing.table.TableModel a0) { super(); }
    public void tableChanged(javax.swing.event.TableModelEvent a0) { return; }
    public java.awt.Dimension getPreferredScrollableViewportSize() { return null; }
    public int getScrollableUnitIncrement(java.awt.Rectangle a0, int a1, int a2) { return 0; }
    public int getScrollableBlockIncrement(java.awt.Rectangle a0, int a1, int a2) { return 0; }
    public boolean getScrollableTracksViewportWidth() { return false; }
    public boolean getScrollableTracksViewportHeight() { return false; }
    public void columnAdded(javax.swing.event.TableColumnModelEvent a0) { return; }
    public void columnRemoved(javax.swing.event.TableColumnModelEvent a0) { return; }
    public void columnMoved(javax.swing.event.TableColumnModelEvent a0) { return; }
    public void columnMarginChanged(javax.swing.event.ChangeEvent a0) { return; }
    public void columnSelectionChanged(javax.swing.event.ListSelectionEvent a0) { return; }
    public void valueChanged(javax.swing.event.ListSelectionEvent a0) { return; }
    public void editingStopped(javax.swing.event.ChangeEvent a0) { return; }
    public void editingCanceled(javax.swing.event.ChangeEvent a0) { return; }
    public void sorterChanged(javax.swing.event.RowSorterEvent a0) { return; }
}
