package javax.swing;

/**
 * Data-only stub for {@code javax.swing.JTabbedPane}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class JTabbedPane extends javax.swing.JComponent implements javax.accessibility.Accessible, javax.swing.SwingConstants {
    public JTabbedPane(int a0) { super(); }
    public void addChangeListener(javax.swing.event.ChangeListener a0) { return; }
    public void addMouseListener(java.awt.event.MouseListener a0) { return; }
    public java.awt.Rectangle getBoundsAt(int a0) { return null; }
    public int getHeight() { return 0; }
    public java.awt.Insets getInsets() { return null; }
    public java.awt.Component getSelectedComponent() { return null; }
    public int getSelectedIndex() { return 0; }
    public int getTabCount() { return 0; }
    public int getTabLayoutPolicy() { return 0; }
    public int getTabPlacement() { return 0; }
    public int getWidth() { return 0; }
    public void insertTab(java.lang.String a0, javax.swing.Icon a1, java.awt.Component a2, java.lang.String a3, int a4) { return; }
    public boolean isEnabled() { return false; }
    public boolean isEnabledAt(int a0) { return false; }
    public boolean isVisible() { return false; }
    public void putClientProperty(java.lang.Object a0, java.lang.Object a1) { return; }
    public void remove(java.awt.Component a0) { return; }
    public void setBackground(java.awt.Color a0) { return; }
    public void setOpaque(boolean a0) { return; }
    public void setSelectedIndex(int a0) { return; }
    public void setVisible(boolean a0) { return; }
}
