package javax.swing;

/**
 * Data-only stub for {@code javax.swing.JTextArea}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class JTextArea extends javax.swing.text.JTextComponent {
    public JTextArea() { super(); }
    public JTextArea(java.lang.String a0) { super(); }
    public void addFocusListener(java.awt.event.FocusListener a0) { return; }
    public javax.swing.ActionMap getActionMap() { return null; }
    public javax.swing.text.Document getDocument() { return null; }
    public javax.swing.InputMap getInputMap() { return null; }
    public void setBackground(java.awt.Color a0) { return; }
    public void setBorder(javax.swing.border.Border a0) { return; }
    public void setEditable(boolean a0) { return; }
    public void setFont(java.awt.Font a0) { return; }
    public void setForeground(java.awt.Color a0) { return; }
    public void setLineWrap(boolean a0) { return; }
    public void setOpaque(boolean a0) { return; }
    public void setTabSize(int a0) { return; }
    public void setText(java.lang.String a0) { return; }
    public void setWrapStyleWord(boolean a0) { return; }
}
