package javax.swing;

/**
 * Data-only stub for {@code javax.swing.JTextField}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class JTextField extends javax.swing.text.JTextComponent implements javax.swing.SwingConstants {
    public JTextField() { super(); }
    public void addActionListener(java.awt.event.ActionListener a0) { return; }
    public void addFocusListener(java.awt.event.FocusListener a0) { return; }
    public void addKeyListener(java.awt.event.KeyListener a0) { return; }
    public void addMouseListener(java.awt.event.MouseListener a0) { return; }
    public void addMouseMotionListener(java.awt.event.MouseMotionListener a0) { return; }
    public javax.swing.text.Document getDocument() { return null; }
    public java.awt.event.MouseListener[] getMouseListeners() { return null; }
    public java.lang.String getText() { return null; }
    public boolean hasFocus() { return false; }
    public boolean isEditable() { return false; }
    public void removeKeyListener(java.awt.event.KeyListener a0) { return; }
    public void removeMouseListener(java.awt.event.MouseListener a0) { return; }
    public boolean requestFocusInWindow() { return false; }
    public void selectAll() { return; }
    public void setBackground(java.awt.Color a0) { return; }
    public void setBorder(javax.swing.border.Border a0) { return; }
    public void setEditable(boolean a0) { return; }
    public void setEnabled(boolean a0) { return; }
    public void setFocusable(boolean a0) { return; }
    public void setForeground(java.awt.Color a0) { return; }
    public void setHorizontalAlignment(int a0) { return; }
    public void setOpaque(boolean a0) { return; }
    public void setPreferredSize(java.awt.Dimension a0) { return; }
    public void setSelectedTextColor(java.awt.Color a0) { return; }
    public void setSelectionColor(java.awt.Color a0) { return; }
    public void setText(java.lang.String a0) { return; }
    public void setToolTipText(java.lang.String a0) { return; }
}
