package javax.swing;

/**
 * Data-only stub for {@code javax.swing.JTree}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class JTree extends javax.swing.JComponent implements javax.swing.Scrollable, javax.accessibility.Accessible {
    public JTree(javax.swing.tree.TreeModel a0) { super(); }
    public JTree(javax.swing.tree.TreeNode a0) { super(); }
    public void addTreeSelectionListener(javax.swing.event.TreeSelectionListener a0) { return; }
    public void collapsePath(javax.swing.tree.TreePath a0) { return; }
    public java.lang.Object getLastSelectedPathComponent() { return null; }
    public javax.swing.tree.TreeSelectionModel getSelectionModel() { return null; }
    public void setBorder(javax.swing.border.Border a0) { return; }
    public void setExpandsSelectedPaths(boolean a0) { return; }
    public void setModel(javax.swing.tree.TreeModel a0) { return; }
    public void setRootVisible(boolean a0) { return; }
    public void setSelectionPath(javax.swing.tree.TreePath a0) { return; }
    public void setShowsRootHandles(boolean a0) { return; }
    public java.awt.Dimension getPreferredScrollableViewportSize() { return null; }
    public int getScrollableUnitIncrement(java.awt.Rectangle a0, int a1, int a2) { return 0; }
    public int getScrollableBlockIncrement(java.awt.Rectangle a0, int a1, int a2) { return 0; }
    public boolean getScrollableTracksViewportWidth() { return false; }
    public boolean getScrollableTracksViewportHeight() { return false; }
}
