package javax.swing;

/**
 * Data-only stub for {@code javax.swing.JViewport}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class JViewport extends javax.swing.JComponent implements javax.accessibility.Accessible {
    public JViewport() { super(); }
    public void addChangeListener(javax.swing.event.ChangeListener a0) { return; }
    public void removeChangeListener(javax.swing.event.ChangeListener a0) { return; }
    public void setBackground(java.awt.Color a0) { return; }
}
