package javax.swing;

/**
 * Data-only stub for {@code javax.swing.PopupFactory}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class PopupFactory {
    public PopupFactory() { }
    public javax.swing.Popup getPopup(java.awt.Component a0, java.awt.Component a1, int a2, int a3, boolean a4) { return null; }
}
