package javax.swing;

/**
 * Data-only stub for {@code javax.swing.SpinnerNumberModel}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class SpinnerNumberModel extends javax.swing.AbstractSpinnerModel {
    public SpinnerNumberModel(double a0, double a1, double a2, double a3) { super(); }
    public SpinnerNumberModel(int a0, int a1, int a2, int a3) { super(); }
    public java.lang.Object getValue() { return null; }
    public void setValue(java.lang.Object a0) { return; }
    public java.lang.Object getNextValue() { return null; }
    public java.lang.Object getPreviousValue() { return null; }
}
