package javax.swing;

/**
 * Data-only stub for {@code javax.swing.ToolTipManager}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public final class ToolTipManager extends java.awt.event.MouseAdapter implements java.awt.event.MouseMotionListener {
    public ToolTipManager() { super(); }
    public void setDismissDelay(int a0) { return; }
    public void setInitialDelay(int a0) { return; }
    public void setLightWeightPopupEnabled(boolean a0) { return; }
    public static javax.swing.ToolTipManager sharedInstance() { return null; }
}
