package javax.swing;

/**
 * Data-only stub for {@code javax.swing.UIManager}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class UIManager {
    public static boolean getBoolean(java.lang.Object a0) { return false; }
    public static java.lang.String getCrossPlatformLookAndFeelClassName() { return null; }
    public static javax.swing.LookAndFeel getLookAndFeel() { return null; }
    public static void setLookAndFeel(java.lang.String a0) { return; }
}
