package javax.management;

/**
 * Data-only stub for {@code javax.management.MBeanServer}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public abstract interface MBeanServer extends javax.management.MBeanServerConnection {
    default java.lang.Object invoke(javax.management.ObjectName a0, java.lang.String a1, java.lang.Object[] a2, java.lang.String[] a3) { return null; }
}
