package javax.management;

/**
 * Data-only stub for {@code javax.management.ObjectName}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class ObjectName implements javax.management.QueryExp {
    public ObjectName(java.lang.String a0) { }
    public int compareTo(java.lang.Object a0) { return 0; }
    public boolean apply(javax.management.ObjectName a0) { return false; }
    public void setMBeanServer(javax.management.MBeanServer a0) { return; }
}
