package javax.swing.filechooser;

/**
 * Data-only stub for {@code javax.swing.filechooser.FileNameExtensionFilter}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public final class FileNameExtensionFilter extends javax.swing.filechooser.FileFilter {
    public FileNameExtensionFilter(java.lang.String a0, java.lang.String[] a1) { super(); }
    public boolean accept(java.io.File a0) { return false; }
    public java.lang.String getDescription() { return null; }
}
