package javax.swing.event;

/**
 * Data-only stub for {@code javax.swing.event.HyperlinkEvent}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class HyperlinkEvent extends java.util.EventObject {
    public HyperlinkEvent() { super((java.lang.Object) null); }
    public javax.swing.event.HyperlinkEvent.EventType getEventType() { return null; }
    public java.net.URL getURL() { return null; }

    public final static class EventType {
        public static final javax.swing.event.HyperlinkEvent.EventType ACTIVATED = null;
    }
}
