package javax.swing.event;

/**
 * Data-only stub for {@code javax.swing.event.TreeSelectionEvent}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class TreeSelectionEvent extends java.util.EventObject {
    public TreeSelectionEvent() { super((java.lang.Object) null); }
    public javax.swing.tree.TreePath getNewLeadSelectionPath() { return null; }
}
