package javax.swing.text;

/**
 * Data-only stub for {@code javax.swing.text.DocumentFilter}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class DocumentFilter {
    public DocumentFilter() { }
    public void insertString(javax.swing.text.DocumentFilter.FilterBypass a0, int a1, java.lang.String a2, javax.swing.text.AttributeSet a3) { return; }
    public void replace(javax.swing.text.DocumentFilter.FilterBypass a0, int a1, int a2, java.lang.String a3, javax.swing.text.AttributeSet a4) { return; }

    public abstract static class FilterBypass {
        public javax.swing.text.Document getDocument() { return null; }
    }
}
