package javax.swing.text;

/**
 * Data-only stub for {@code javax.swing.text.Document}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public abstract interface Document {
    default void addDocumentListener(javax.swing.event.DocumentListener a0) { return; }
    default void addUndoableEditListener(javax.swing.event.UndoableEditListener a0) { return; }
    default int getLength() { return 0; }
    default java.lang.String getText(int a0, int a1) { return null; }
    default void insertString(int a0, java.lang.String a1, javax.swing.text.AttributeSet a2) { return; }
    default void remove(int a0, int a1) { return; }
}
