package javax.swing.text;

/**
 * Data-only stub for {@code javax.swing.text.JTextComponent}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public abstract class JTextComponent extends javax.swing.JComponent implements javax.swing.Scrollable, javax.accessibility.Accessible {
    public JTextComponent() { super(); }
    public void addFocusListener(java.awt.event.FocusListener a0) { return; }
    public javax.swing.text.Document getDocument() { return null; }
    public int getSelectionEnd() { return 0; }
    public int getSelectionStart() { return 0; }
    public java.lang.String getText() { return null; }
    public java.lang.String getText(int a0, int a1) { return null; }
    public void select(int a0, int a1) { return; }
    public void setBorder(javax.swing.border.Border a0) { return; }
    public void setText(java.lang.String a0) { return; }
}
