package java.beans;

/**
 * Data-only stub for {@code java.beans.PropertyChangeEvent}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class PropertyChangeEvent extends java.util.EventObject {
    public PropertyChangeEvent() { super((java.lang.Object) null); }
    public java.lang.String getPropertyName() { return null; }
    public java.lang.Object getSource() { return null; }
}
