package java.beans;

/**
 * Data-only stub for {@code java.beans.PropertyChangeSupport}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class PropertyChangeSupport {
    public PropertyChangeSupport(java.lang.Object a0) { }
    public void addPropertyChangeListener(java.beans.PropertyChangeListener a0) { return; }
    public void firePropertyChange(java.lang.String a0, boolean a1, boolean a2) { return; }
    public void removePropertyChangeListener(java.beans.PropertyChangeListener a0) { return; }
}
