package javax.swing.undo;

/**
 * Data-only stub for {@code javax.swing.undo.UndoManager}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class UndoManager extends javax.swing.undo.CompoundEdit implements javax.swing.event.UndoableEditListener {
    public UndoManager() { super(); }
    public boolean addEdit(javax.swing.undo.UndoableEdit a0) { return false; }
    public boolean canRedo() { return false; }
    public boolean canUndo() { return false; }
    public void redo() { return; }
    public void setLimit(int a0) { return; }
    public void undo() { return; }
    public void undoableEditHappened(javax.swing.event.UndoableEditEvent a0) { return; }
}
