package com.sun.net.httpserver;

/**
 * Data-only stub for {@code com.sun.net.httpserver.HttpExchange}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public abstract class HttpExchange implements com.sun.net.httpserver.Request {
    public void close() { return; }
    public java.net.URI getRequestURI() { return null; }
    public java.io.OutputStream getResponseBody() { return null; }
    public com.sun.net.httpserver.Headers getResponseHeaders() { return null; }
    public void sendResponseHeaders(int a0, long a1) { return; }
}
