package com.sun.net.httpserver;

/**
 * Data-only stub for {@code com.sun.net.httpserver.HttpServer}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public abstract class HttpServer {
    public static com.sun.net.httpserver.HttpServer create(java.net.InetSocketAddress a0, int a1) { return null; }
    public com.sun.net.httpserver.HttpContext createContext(java.lang.String a0, com.sun.net.httpserver.HttpHandler a1) { return null; }
    public java.net.InetSocketAddress getAddress() { return null; }
    public void start() { return; }
    public void stop(int a0) { return; }
}
