package java.awt.event;

/**
 * Data-only stub for {@code java.awt.event.ItemEvent}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class ItemEvent extends java.awt.AWTEvent {
    public ItemEvent() { super(); }
    public int getStateChange() { return 0; }
}
