package java.awt.event;

/**
 * Data-only stub for {@code java.awt.event.WindowAdapter}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public abstract class WindowAdapter implements java.awt.event.WindowListener, java.awt.event.WindowStateListener, java.awt.event.WindowFocusListener {
    public WindowAdapter() { }
    public void windowOpened(java.awt.event.WindowEvent a0) { return; }
    public void windowClosing(java.awt.event.WindowEvent a0) { return; }
    public void windowClosed(java.awt.event.WindowEvent a0) { return; }
    public void windowIconified(java.awt.event.WindowEvent a0) { return; }
    public void windowDeiconified(java.awt.event.WindowEvent a0) { return; }
    public void windowActivated(java.awt.event.WindowEvent a0) { return; }
    public void windowDeactivated(java.awt.event.WindowEvent a0) { return; }
    public void windowStateChanged(java.awt.event.WindowEvent a0) { return; }
    public void windowGainedFocus(java.awt.event.WindowEvent a0) { return; }
    public void windowLostFocus(java.awt.event.WindowEvent a0) { return; }
}
