package javax.swing.tree;

/**
 * Data-only stub for {@code javax.swing.tree.DefaultTreeModel}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class DefaultTreeModel implements javax.swing.tree.TreeModel {
    public DefaultTreeModel(javax.swing.tree.TreeNode a0) { }
    public javax.swing.tree.TreeNode[] getPathToRoot(javax.swing.tree.TreeNode a0) { return null; }
    public java.lang.Object getRoot() { return null; }
    public boolean isLeaf(java.lang.Object a0) { return false; }
    public int getChildCount(java.lang.Object a0) { return 0; }
    public java.lang.Object getChild(java.lang.Object a0, int a1) { return null; }
    public void valueForPathChanged(javax.swing.tree.TreePath a0, java.lang.Object a1) { return; }
    public void removeTreeModelListener(javax.swing.event.TreeModelListener a0) { return; }
    public void addTreeModelListener(javax.swing.event.TreeModelListener a0) { return; }
    public int getIndexOfChild(java.lang.Object a0, java.lang.Object a1) { return 0; }
}
