package javax.swing.tree;

/**
 * Data-only stub for {@code javax.swing.tree.DefaultMutableTreeNode}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class DefaultMutableTreeNode implements javax.swing.tree.MutableTreeNode {
    public DefaultMutableTreeNode() { }
    public DefaultMutableTreeNode(java.lang.Object a0) { }
    public void add(javax.swing.tree.MutableTreeNode a0) { return; }
    public java.util.Enumeration children() { return null; }
    public javax.swing.tree.TreeNode getChildBefore(javax.swing.tree.TreeNode a0) { return null; }
    public int getChildCount() { return 0; }
    public int getIndex(javax.swing.tree.TreeNode a0) { return 0; }
    public javax.swing.tree.TreeNode getParent() { return null; }
    public javax.swing.tree.TreeNode[] getPath() { return null; }
    public java.lang.Object getUserObject() { return null; }
    public void remove(int a0) { return; }
    public void removeAllChildren() { return; }
    public void insert(javax.swing.tree.MutableTreeNode a0, int a1) { return; }
    public void setParent(javax.swing.tree.MutableTreeNode a0) { return; }
    public void setUserObject(java.lang.Object a0) { return; }
    public void removeFromParent() { return; }
    public boolean isLeaf() { return false; }
    public boolean getAllowsChildren() { return false; }
    public javax.swing.tree.TreeNode getChildAt(int a0) { return null; }
}
