package javax.swing.tree;

/**
 * Data-only stub for {@code javax.swing.tree.TreeSelectionModel}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public abstract interface TreeSelectionModel {
    default void addSelectionPath(javax.swing.tree.TreePath a0) { return; }
    default void addTreeSelectionListener(javax.swing.event.TreeSelectionListener a0) { return; }
    default void clearSelection() { return; }
}
