package javax.sound.sampled;

/**
 * Data-only stub for {@code javax.sound.sampled.AudioSystem}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class AudioSystem {
    public static javax.sound.sampled.AudioInputStream getAudioInputStream(java.io.InputStream a0) { return null; }
    public static javax.sound.sampled.Clip getClip() { return null; }
    public static javax.sound.sampled.Line getLine(javax.sound.sampled.Line.Info a0) { return null; }
}
