package javax.sound.sampled;

/**
 * Data-only stub for {@code javax.sound.sampled.AudioFormat}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class AudioFormat {
    public AudioFormat(float a0, int a1, int a2, boolean a3, boolean a4) { }
}
