package javax.sound.sampled;

/**
 * Data-only stub for {@code javax.sound.sampled.Clip}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public abstract interface Clip extends javax.sound.sampled.DataLine {
    default void addLineListener(javax.sound.sampled.LineListener a0) { return; }
    default void close() { return; }
    default void open(javax.sound.sampled.AudioInputStream a0) { return; }
}
