package javax.sound.sampled;

/**
 * Data-only stub for {@code javax.sound.sampled.DataLine}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public abstract interface DataLine extends javax.sound.sampled.Line {
    default javax.sound.sampled.Control getControl(javax.sound.sampled.Control.Type a0) { return null; }
    default void start() { return; }

    public static class Info extends javax.sound.sampled.Line.Info {
        public Info(java.lang.Class a0, javax.sound.sampled.AudioFormat a1, int a2) { super(); }
    }
}
