package javax.sound.sampled;

/**
 * Data-only stub for {@code javax.sound.sampled.FloatControl}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public abstract class FloatControl extends javax.sound.sampled.Control {
    public FloatControl() { super(); }
    public void setValue(float a0) { return; }

    public static class Type extends javax.sound.sampled.Control.Type {
        public static final javax.sound.sampled.FloatControl.Type MASTER_GAIN = null;
        public Type() { super(); }
    }
}
