package javax.sound.sampled;

/**
 * Data-only stub for {@code javax.sound.sampled.LineEvent}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class LineEvent extends java.util.EventObject {
    public LineEvent() { super((java.lang.Object) null); }
    public javax.sound.sampled.LineEvent.Type getType() { return null; }

    public static class Type {
        public static final javax.sound.sampled.LineEvent.Type STOP = null;
    }
}
