package javax.sound.sampled;

/**
 * Data-only stub for {@code javax.sound.sampled.SourceDataLine}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public abstract interface SourceDataLine extends javax.sound.sampled.DataLine {
    default int available() { return 0; }
    default void close() { return; }
    default void flush() { return; }
    default void open() { return; }
    default void start() { return; }
    default int write(byte[] a0, int a1, int a2) { return 0; }
}
