package javax.swing.table;

/**
 * Data-only stub for {@code javax.swing.table.AbstractTableModel}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public abstract class AbstractTableModel implements javax.swing.table.TableModel {
    public AbstractTableModel() { }
    public void fireTableStructureChanged() { return; }
    public int getRowCount() { return 0; }
    public int getColumnCount() { return 0; }
    public java.lang.String getColumnName(int a0) { return null; }
    public java.lang.Class getColumnClass(int a0) { return null; }
    public java.lang.Object getValueAt(int a0, int a1) { return null; }
    public void setValueAt(java.lang.Object a0, int a1, int a2) { return; }
    public boolean isCellEditable(int a0, int a1) { return false; }
    public void removeTableModelListener(javax.swing.event.TableModelListener a0) { return; }
    public void addTableModelListener(javax.swing.event.TableModelListener a0) { return; }
}
