package java.awt;

/**
 * Data-only stub for {@code java.awt.CardLayout}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class CardLayout implements java.awt.LayoutManager2 {
    public CardLayout() { }
    public void show(java.awt.Container a0, java.lang.String a1) { return; }
    public void addLayoutComponent(java.awt.Component a0, java.lang.Object a1) { return; }
    public java.awt.Dimension maximumLayoutSize(java.awt.Container a0) { return null; }
    public float getLayoutAlignmentX(java.awt.Container a0) { return 0f; }
    public float getLayoutAlignmentY(java.awt.Container a0) { return 0f; }
    public void invalidateLayout(java.awt.Container a0) { return; }
    public void addLayoutComponent(java.lang.String a0, java.awt.Component a1) { return; }
    public void removeLayoutComponent(java.awt.Component a0) { return; }
    public java.awt.Dimension minimumLayoutSize(java.awt.Container a0) { return null; }
    public java.awt.Dimension preferredLayoutSize(java.awt.Container a0) { return null; }
    public void layoutContainer(java.awt.Container a0) { return; }
}
