package java.awt;

/**
 * Data-only stub for {@code java.awt.GridLayout}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class GridLayout implements java.awt.LayoutManager {
    public GridLayout(int a0, int a1) { }
    public GridLayout(int a0, int a1, int a2, int a3) { }
    public int getColumns() { return 0; }
    public int getHgap() { return 0; }
    public int getRows() { return 0; }
    public int getVgap() { return 0; }
    public void addLayoutComponent(java.lang.String a0, java.awt.Component a1) { return; }
    public void removeLayoutComponent(java.awt.Component a0) { return; }
    public java.awt.Dimension minimumLayoutSize(java.awt.Container a0) { return null; }
    public java.awt.Dimension preferredLayoutSize(java.awt.Container a0) { return null; }
    public void layoutContainer(java.awt.Container a0) { return; }
}
