package java.awt;

/**
 * Data-only stub for {@code java.awt.KeyboardFocusManager}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public abstract class KeyboardFocusManager implements java.awt.KeyEventDispatcher, java.awt.KeyEventPostProcessor {
    public void addKeyEventDispatcher(java.awt.KeyEventDispatcher a0) { return; }
    public java.awt.Window getActiveWindow() { return null; }
    public static java.awt.KeyboardFocusManager getCurrentKeyboardFocusManager() { return null; }
}
