package java.awt;

/**
 * Data-only stub for {@code java.awt.SystemTray}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class SystemTray {
    public void add(java.awt.TrayIcon a0) { return; }
    public static java.awt.SystemTray getSystemTray() { return null; }
    public static boolean isSupported() { return false; }
}
