package java.awt;

/**
 * Data-only stub for {@code java.awt.Taskbar}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class Taskbar {
    public static java.awt.Taskbar getTaskbar() { return null; }
    public boolean isSupported(java.awt.Taskbar.Feature a0) { return false; }
    public static boolean isTaskbarSupported() { return false; }
    public void requestUserAttention(boolean a0, boolean a1) { return; }
    public void requestWindowUserAttention(java.awt.Window a0) { return; }

    public static enum Feature {
        USER_ATTENTION_WINDOW,
        USER_ATTENTION,
        PROGRESS_VALUE_WINDOW,
        PROGRESS_VALUE,
        PROGRESS_STATE_WINDOW,
        MENU,
        ICON_IMAGE,
        ICON_BADGE_IMAGE_WINDOW,
        ICON_BADGE_NUMBER,
        ICON_BADGE_TEXT,
    }
}
