package java.awt;

/**
 * Data-only stub for {@code java.awt.TrayIcon}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public class TrayIcon {
    public TrayIcon(java.awt.Image a0, java.lang.String a1) { }
    public void addMouseListener(java.awt.event.MouseListener a0) { return; }
    public void displayMessage(java.lang.String a0, java.lang.String a1, java.awt.TrayIcon.MessageType a2) { return; }
    public void setImageAutoSize(boolean a0) { return; }

    public static enum MessageType {
        NONE,
        INFO,
        WARNING,
        ERROR,
    }
}
