package javax.swing.text.html;

/**
 * Data-only stub for {@code javax.swing.text.html.HTMLEditorKit}.
 *
 * The Android runtime has no java.desktop, so every type the pre-compiled RuneLite
 * client jar references has to exist here with the same name, hierarchy and member
 * signatures (the member set is taken from the real call sites). Nothing paints, lays
 * out or dispatches events: the native side panel replaces the desktop Swing shell.
 * Generated by tools/gen_stubs.py -- do not hand-edit.
 */
public abstract class HTMLEditorKit extends javax.swing.text.StyledEditorKit implements javax.accessibility.Accessible {
    public HTMLEditorKit() { super(); }
    public javax.swing.text.html.StyleSheet getStyleSheet() { return null; }
}
